### PR TITLE
fix installation error b/c of small letters in class names

### PR DESCRIPTION
**Pull request by polkan-msk**
installation on M2.1.12 failed with following error
  [ReflectionException]
  Class Webfixit\CacheHostsManager\Console\Command\add does not exist
here is a fix

### CODE REVIEW

**Comment by wiardvanrij** [comment]
Thank you, just for my person information: do you use windows? Might explain the case sensitivity or something. 

Will create a new release soon.

**Comment by polkan-msk** [comment]
No, I don't. I got that error on CentOS 7 system. I suppose that's more about php version. Php's case sensitivity approach is rather messy. My server is on php 7.0.30.

**Comment by wiardvanrij** [comment]
@polkan-msk thanks again, new release should be available with version 1.0.1!

**Comment by polkan-msk** [comment]
Thanks! Will it be available to install via composer? I still get v 1.0.0 when trying to install it.

**Comment by wiardvanrij** [comment]
Yes, should be available now: https://packagist.org/packages/webfixit/cachehostsmanager

**Pull request merged**
